Book.create!(author: "Jane Austen", title: "Pride and Prejudice")
Book.create!(author: "F. Scott Fitzgerald", title: "The Great Gatsby")
Book.create!(author: "George Orwell", title: "1984")
Book.create!(author: "Harper Lee", title: "To Kill a Mockingbird")
Book.create!(author: "J.K. Rowling", title: "Harry Potter and the Sorcerer's Stone")
Book.create!(author: "Gabriel García Márquez", title: "One Hundred Years of Solitude")
Book.create!(author: "Leo Tolstoy", title: "Anna Karenina")
Book.create!(author: "Mark Twain", title: "The Adventures of Huckleberry Finn")
Book.create!(author: "Charles Dickens", title: "A Tale of Two Cities")
Book.create!(author: "Toni Morrison", title: "Beloved")
Book.create!(author: "Ernest Hemingway", title: "The Old Man and the Sea")
Book.create!(author: "Virginia Woolf", title: "Mrs. Dalloway")
Book.create!(author: "Salman Rushdie", title: "Midnight's Children")
Book.create!(author: "Margaret Atwood", title: "The Handmaid's Tale")
Book.create!(author: "Kazuo Ishiguro", title: "Never Let Me Go")
Book.create!(author: "Albert Camus", title: "The Stranger")
Book.create!(author: "Milan Kundera", title: "The Unbearable Lightness of Being")
Book.create!(author: "Haruki Murakami", title: "Norwegian Wood")
Book.create!(author: "J.R.R. Tolkien", title: "The Lord of the Rings")
Book.create!(author: "Agatha Christie", title: "Murder on the Orient Express")
Book.create!(author: "John Steinbeck", title: "The Grapes of Wrath")
Book.create!(author: "Isabel Allende", title: "The House of the Spirits")
Book.create!(author: "Aldous Huxley", title: "Brave New World")
Book.create!(author: "Emily Brontë", title: "Wuthering Heights")
Book.create!(author: "Kurt Vonnegut", title: "Slaughterhouse-Five")
Book.create!(author: "Chinua Achebe", title: "Things Fall Apart")
Book.create!(author: "Virginia Woolf", title: "To the Lighthouse")
Book.create!(author: "Gabriel García Márquez", title: "Love in the Time of Cholera")
Book.create!(author: "Oscar Wilde", title: "The Picture of Dorian Gray")
Book.create!(author: "Franz Kafka", title: "The Metamorphosis")
Book.create!(author: "Zora Neale Hurston", title: "Their Eyes Were Watching God")
Book.create!(author: "George Orwell", title: "Animal Farm")
Book.create!(author: "Daphne du Maurier", title: "Rebecca")
Book.create!(author: "Milan Kundera", title: "The Book of Laughter and Forgetting")
Book.create!(author: "Leo Tolstoy", title: "War and Peace")
Book.create!(author: "Margaret Atwood", title: "Oryx and Crake")
Book.create!(author: "Haruki Murakami", title: "Kafka on the Shore")
Book.create!(author: "Fyodor Dostoevsky", title: "Crime and Punishment")
Book.create!(author: "Gabriel García Márquez", title: "Chronicle of a Death Foretold")
Book.create!(author: "J.D. Salinger", title: "The Catcher in the Rye")
Book.create!(author: "Virginia Woolf", title: "Orlando")
Book.create!(author: "Kazuo Ishiguro", title: "The Remains of the Day")
Book.create!(author: "Ernest Hemingway", title: "For Whom the Bell Tolls")
Book.create!(author: "Charlotte Brontë", title: "Jane Eyre")
Book.create!(author: "Salman Rushdie", title: "The Satanic Verses")
Book.create!(author: "Albert Camus", title: "The Plague")
Book.create!(author: "Milan Kundera", title: "The Joke")
Book.create!(author: "Gabriel García Márquez", title: "Of Love and Other Demons")
Book.create!(author: "Virginia Woolf", title: "Jacob's Room")
Book.create!(author: "F. Scott Fitzgerald", title: "Tender Is the Night")